project:
  type: website

website:
  title: "Furong Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Marketing Analytics
        menu:
          - text: Lobsterland Consumer Insights 
            href: marketing_analytics.qmd                    
          - text: Cruise Booking Cancellation Analysis       
            href: classification.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-expand: 2

execute:
  echo: true
  eval: true
  code-fold: true



